// ============================================================
// HP Labs — OWASP Mobile (MASVS v2) Adapter
// Authoritative mobile vulnerability list from
// OWASP Mobile Application Security Verification Standard v2.
// Reference: https://mas.owasp.org/MASVS/
// ============================================================

import { BaseAdapter } from "@/lib/detector/sourceAdapters/BaseAdapter";
import type { AdapterResult, DetectorVulnerability } from "@/lib/detector/detectorTypes";

const SOURCE_REF = "https://mas.owasp.org/MASVS/";

const OWASP_MOBILE_VULNS: Omit<DetectorVulnerability, "canonicalId" | "normalizedName" | "sourceAdapterId" | "domainId" | "detectedAt">[] = [
  // ── Information ──────────────────────────────────────────────
  { name: "APK Decompilation & Asset Extraction", severity: "information", sourceIdentifiers: ["masvs-info-apk-decompile"], cwe: ["CWE-200"], cve: [], cvssScore: 0.0, description: "Reverse engineering APK to extract source code and embedded assets.", labFeasible: true, firstDiscoveredYear: 2010, references: [SOURCE_REF, "https://mas.owasp.org/MASTG/tests/android/MASVS-RESILIENCE/"] },
  { name: "Android Manifest Permission Analysis", severity: "information", sourceIdentifiers: ["masvs-info-manifest-perms"], cwe: ["CWE-276"], cve: [], cvssScore: 0.0, description: "Reviewing AndroidManifest.xml for dangerous and unnecessary permissions.", labFeasible: true, firstDiscoveredYear: 2008, references: [SOURCE_REF] },
  { name: "Mobile Traffic Interception Setup (HTTP Proxy)", severity: "information", sourceIdentifiers: ["masvs-info-traffic-intercept"], cwe: ["CWE-319"], cve: [], cvssScore: 0.0, description: "Configuring Burp Suite as mobile device proxy to inspect API calls.", labFeasible: true, firstDiscoveredYear: 2012, references: [SOURCE_REF] },
  { name: "SSL Pinning Detection & Bypass Reconnaissance", severity: "information", sourceIdentifiers: ["masvs-info-ssl-pinning-detect"], cwe: ["CWE-297"], cve: [], cvssScore: 0.0, description: "Identifying SSL certificate pinning implementation in mobile apps.", labFeasible: true, firstDiscoveredYear: 2012, references: [SOURCE_REF, "https://mas.owasp.org/MASTG/tests/android/MASVS-NETWORK/"] },
  { name: "iOS Plist File Sensitive Data Analysis", severity: "information", sourceIdentifiers: ["masvs-info-ios-plist"], cwe: ["CWE-312"], cve: [], cvssScore: 0.0, description: "Property list files exposing API keys, endpoints, or credentials.", labFeasible: true, firstDiscoveredYear: 2008, references: [SOURCE_REF] },
  { name: "Exported Activity & Intent Filter Discovery", severity: "information", sourceIdentifiers: ["masvs-info-exported-activity"], cwe: ["CWE-926"], cve: [], cvssScore: 0.0, description: "Identifying exported Android activities accessible by third-party apps.", labFeasible: true, firstDiscoveredYear: 2009, references: [SOURCE_REF] },
  { name: "Mobile App Version & Build Fingerprinting", severity: "information", sourceIdentifiers: ["masvs-info-app-fingerprint"], cwe: ["CWE-200"], cve: [], cvssScore: 0.0, description: "Extracting build number, SDK version, and library versions from APK.", labFeasible: true, firstDiscoveredYear: 2010, references: [SOURCE_REF] },
  { name: "SQLite Database File Extraction (Non-Encrypted)", severity: "information", sourceIdentifiers: ["masvs-info-sqlite-unenc"], cwe: ["CWE-312"], cve: [], cvssScore: 0.0, description: "Extracting plaintext SQLite databases from app data directory.", labFeasible: true, firstDiscoveredYear: 2009, references: [SOURCE_REF] },
  { name: "Shared Preferences Sensitive Data Exposure", severity: "information", sourceIdentifiers: ["masvs-info-shared-prefs"], cwe: ["CWE-312"], cve: [], cvssScore: 0.0, description: "Tokens, credentials, and PII stored in plaintext SharedPreferences XML.", labFeasible: true, firstDiscoveredYear: 2009, references: [SOURCE_REF] },
  { name: "Network Traffic Certificate Transparency Audit", severity: "information", sourceIdentifiers: ["masvs-info-cert-transparency"], cwe: ["CWE-295"], cve: [], cvssScore: 0.0, description: "Checking whether the app enforces certificate transparency logs.", labFeasible: true, firstDiscoveredYear: 2013, references: [SOURCE_REF] },
  { name: "Backup Flag Analysis — Android allowBackup", severity: "information", sourceIdentifiers: ["masvs-info-android-backup"], cwe: ["CWE-530"], cve: [], cvssScore: 0.0, description: "android:allowBackup=true enables data extraction via adb backup.", labFeasible: true, firstDiscoveredYear: 2011, references: [SOURCE_REF] },
  { name: "Firebase Realtime Database Misconfiguration", severity: "information", sourceIdentifiers: ["masvs-info-firebase-misconfig"], cwe: ["CWE-732"], cve: [], cvssScore: 0.0, description: "Publicly readable Firebase databases exposing user data.", labFeasible: true, firstDiscoveredYear: 2016, references: [SOURCE_REF] },
  { name: "Hardcoded Debug Endpoints & Test Credentials", severity: "information", sourceIdentifiers: ["masvs-info-debug-endpoints"], cwe: ["CWE-798"], cve: [], cvssScore: 0.0, description: "Debug API endpoints and hardcoded test credentials in APK.", labFeasible: true, firstDiscoveredYear: 2010, references: [SOURCE_REF] },
  { name: "Log Output Sensitive Data Leakage (Logcat)", severity: "information", sourceIdentifiers: ["masvs-info-logcat-leakage"], cwe: ["CWE-532"], cve: [], cvssScore: 0.0, description: "Tokens, PII, or session data logged to Android Logcat.", labFeasible: true, firstDiscoveredYear: 2009, references: [SOURCE_REF] },
  { name: "App-Level Network Security Configuration Audit", severity: "information", sourceIdentifiers: ["masvs-info-network-security-config"], cwe: ["CWE-319"], cve: [], cvssScore: 0.0, description: "Android network_security_config.xml allowing cleartext traffic.", labFeasible: true, firstDiscoveredYear: 2016, references: [SOURCE_REF] },
  // ── Low ──────────────────────────────────────────────────────
  { name: "Unprotected Broadcast Receiver (Intent Injection)", severity: "low", sourceIdentifiers: ["masvs-low-broadcast-receiver"], cwe: ["CWE-925"], cve: [], cvssScore: 3.1, description: "Exported BroadcastReceiver processes intents from any app.", labFeasible: true, firstDiscoveredYear: 2010, references: [SOURCE_REF] },
  { name: "Tapjacking — Overlay Attack", severity: "low", sourceIdentifiers: ["masvs-low-tapjacking"], cwe: ["CWE-1021"], cve: [], cvssScore: 3.5, description: "Transparent overlay intercepts touch events on target app.", labFeasible: true, firstDiscoveredYear: 2011, references: [SOURCE_REF] },
  { name: "Clipboard Data Exposure (Sensitive Copy/Paste)", severity: "low", sourceIdentifiers: ["masvs-low-clipboard"], cwe: ["CWE-312"], cve: [], cvssScore: 2.5, description: "Sensitive data placed on system clipboard accessible to all apps.", labFeasible: true, firstDiscoveredYear: 2012, references: [SOURCE_REF] },
  { name: "Insecure File Permissions (World-Readable Files)", severity: "low", sourceIdentifiers: ["masvs-low-file-permissions"], cwe: ["CWE-732"], cve: [], cvssScore: 3.3, description: "Internal files created with MODE_WORLD_READABLE permission.", labFeasible: true, firstDiscoveredYear: 2009, references: [SOURCE_REF] },
  { name: "Weak Local Authentication (PIN/Pattern Bypass)", severity: "low", sourceIdentifiers: ["masvs-low-local-auth-bypass"], cwe: ["CWE-287"], cve: [], cvssScore: 3.7, description: "Local PIN or pattern lock bypassable via offline extraction.", labFeasible: true, firstDiscoveredYear: 2013, references: [SOURCE_REF] },
  { name: "Screenshot Capture Vulnerability (FLAG_SECURE Missing)", severity: "low", sourceIdentifiers: ["masvs-low-screenshot"], cwe: ["CWE-359"], cve: [], cvssScore: 2.8, description: "Sensitive screens captured by background apps or task switcher.", labFeasible: true, firstDiscoveredYear: 2011, references: [SOURCE_REF] },
  { name: "Insecure Deep Link Handling (Unvalidated URI Scheme)", severity: "low", sourceIdentifiers: ["masvs-low-deep-link-uri"], cwe: ["CWE-601"], cve: [], cvssScore: 3.5, description: "Custom URL schemes process parameters without validation.", labFeasible: true, firstDiscoveredYear: 2013, references: [SOURCE_REF] },
  { name: "External Storage Sensitive Data Write", severity: "low", sourceIdentifiers: ["masvs-low-external-storage"], cwe: ["CWE-312"], cve: [], cvssScore: 3.3, description: "Sensitive files written to /sdcard/ accessible by any app.", labFeasible: true, firstDiscoveredYear: 2009, references: [SOURCE_REF] },
  { name: "Insecure Session Token in URL (Mobile API)", severity: "low", sourceIdentifiers: ["masvs-low-token-in-url"], cwe: ["CWE-598"], cve: [], cvssScore: 3.1, description: "Authentication tokens passed in mobile API URL query strings.", labFeasible: true, firstDiscoveredYear: 2012, references: [SOURCE_REF] },
  { name: "Weak Cryptographic Algorithm (MD5/SHA1 for Passwords)", severity: "low", sourceIdentifiers: ["masvs-low-weak-crypto"], cwe: ["CWE-327"], cve: [], cvssScore: 3.7, description: "MD5 or SHA1 used to hash passwords in mobile app.", labFeasible: true, firstDiscoveredYear: 2005, references: [SOURCE_REF] },
  // ── Medium ───────────────────────────────────────────────────
  { name: "WebView JavaScript Interface Injection", severity: "medium", sourceIdentifiers: ["masvs-med-webview-js"], cwe: ["CWE-749"], cve: [], cvssScore: 6.1, description: "addJavascriptInterface enables native API calls from WebView JS.", labFeasible: true, firstDiscoveredYear: 2012, references: [SOURCE_REF] },
  { name: "Insecure Biometric Authentication Bypass", severity: "medium", sourceIdentifiers: ["masvs-med-biometric-bypass"], cwe: ["CWE-287"], cve: [], cvssScore: 6.5, description: "Biometric auth falling back to PIN without crypto key binding.", labFeasible: true, firstDiscoveredYear: 2017, references: [SOURCE_REF] },
  { name: "Deep Link Injection — Cross-App Data Theft", severity: "medium", sourceIdentifiers: ["masvs-med-deep-link-injection"], cwe: ["CWE-926"], cve: [], cvssScore: 5.4, description: "Malicious deep links redirect sensitive URI scheme data.", labFeasible: true, firstDiscoveredYear: 2014, references: [SOURCE_REF] },
  { name: "SSL Pinning Bypass via Frida Runtime Hook", severity: "medium", sourceIdentifiers: ["masvs-med-ssl-pinning-frida"], cwe: ["CWE-297"], cve: [], cvssScore: 5.9, description: "Frida script hooks TrustManager to disable certificate pinning.", labFeasible: true, firstDiscoveredYear: 2015, references: [SOURCE_REF] },
  { name: "Root/Jailbreak Detection Bypass", severity: "medium", sourceIdentifiers: ["masvs-med-root-detection-bypass"], cwe: ["CWE-656"], cve: [], cvssScore: 5.1, description: "Bypassing root/jailbreak checks to run restricted features.", labFeasible: true, firstDiscoveredYear: 2012, references: [SOURCE_REF] },
  { name: "Content Provider SQL Injection (Android)", severity: "medium", sourceIdentifiers: ["masvs-med-content-provider-sqli"], cwe: ["CWE-89"], cve: [], cvssScore: 6.5, description: "Exported ContentProvider processes unsanitized SQL projection args.", labFeasible: true, firstDiscoveredYear: 2011, references: [SOURCE_REF] },
  { name: "Unencrypted Sensitive Data in SQLite (Mobile)", severity: "medium", sourceIdentifiers: ["masvs-med-sqlite-unencrypted"], cwe: ["CWE-312"], cve: [], cvssScore: 5.5, description: "Session tokens and PII stored without encryption in SQLite.", labFeasible: true, firstDiscoveredYear: 2010, references: [SOURCE_REF] },
  { name: "Keystore Key Extraction via Backup (Android)", severity: "medium", sourceIdentifiers: ["masvs-med-keystore-backup"], cwe: ["CWE-522"], cve: [], cvssScore: 5.7, description: "Android Keystore keys extractable via ADB backup on rooted device.", labFeasible: true, firstDiscoveredYear: 2013, references: [SOURCE_REF] },
  { name: "Task Hijacking (Android Activity Stack Manipulation)", severity: "medium", sourceIdentifiers: ["masvs-med-task-hijacking"], cwe: ["CWE-285"], cve: [], cvssScore: 5.4, description: "Malicious app steals foreground via launchMode=singleTask.", labFeasible: true, firstDiscoveredYear: 2015, references: [SOURCE_REF] },
  { name: "iOS Keychain Item Accessible When Unlocked Weakness", severity: "medium", sourceIdentifiers: ["masvs-med-ios-keychain-access"], cwe: ["CWE-312"], cve: [], cvssScore: 4.6, description: "Keychain items with kSecAttrAccessibleAlways extracted when device is locked.", labFeasible: true, firstDiscoveredYear: 2011, references: [SOURCE_REF] },
  // ── High ─────────────────────────────────────────────────────
  { name: "Hardcoded Credentials & API Keys in APK", severity: "high", sourceIdentifiers: ["masvs-high-hardcoded-creds"], cwe: ["CWE-798"], cve: [], cvssScore: 8.1, description: "Hardcoded credentials, API keys, and tokens extracted from APK.", labFeasible: true, firstDiscoveredYear: 2010, references: [SOURCE_REF] },
  { name: "Dynamic Code Loading Exploitation", severity: "high", sourceIdentifiers: ["masvs-high-dynamic-code-load"], cwe: ["CWE-494"], cve: [], cvssScore: 8.0, description: "DexClassLoader loads unverified DEX from writable external storage.", labFeasible: true, firstDiscoveredYear: 2012, references: [SOURCE_REF] },
  { name: "Memory Scraping for Cryptographic Secrets", severity: "high", sourceIdentifiers: ["masvs-high-memory-scraping"], cwe: ["CWE-316"], cve: [], cvssScore: 7.5, description: "Process memory dumped to extract in-memory keys and tokens.", labFeasible: true, firstDiscoveredYear: 2015, references: [SOURCE_REF] },
  { name: "WebView Remote Code Execution via File Access", severity: "high", sourceIdentifiers: ["masvs-high-webview-file-access"], cwe: ["CWE-749"], cve: [], cvssScore: 8.8, description: "setAllowFileAccessFromFileURLs enables JS to read arbitrary files.", labFeasible: true, firstDiscoveredYear: 2011, references: [SOURCE_REF] },
  { name: "Man-in-the-Middle via Custom TrustManager", severity: "high", sourceIdentifiers: ["masvs-high-custom-trustmanager"], cwe: ["CWE-295"], cve: [], cvssScore: 7.5, description: "Custom TrustManager trusts all certificates — full MitM.", labFeasible: true, firstDiscoveredYear: 2012, references: [SOURCE_REF] },
  { name: "Insecure Cryptography — Hardcoded IV in AES-CBC", severity: "high", sourceIdentifiers: ["masvs-high-hardcoded-iv"], cwe: ["CWE-329"], cve: [], cvssScore: 7.5, description: "Fixed initialization vector in AES-CBC allows plaintext recovery.", labFeasible: true, firstDiscoveredYear: 2014, references: [SOURCE_REF] },
  { name: "Frida Runtime Injection for Credential Theft", severity: "high", sourceIdentifiers: ["masvs-high-frida-injection"], cwe: ["CWE-94"], cve: [], cvssScore: 8.1, description: "Frida scripts inject into running process to steal session tokens.", labFeasible: true, firstDiscoveredYear: 2015, references: [SOURCE_REF] },
  { name: "Intent Redirection to Private Components", severity: "high", sourceIdentifiers: ["masvs-high-intent-redirect"], cwe: ["CWE-926"], cve: [], cvssScore: 7.7, description: "Exported Activity processes untrusted intent data forwarding to private Activities.", labFeasible: true, firstDiscoveredYear: 2013, references: [SOURCE_REF] },
  { name: "Side-Channel Attack via Auto-Complete Cache", severity: "high", sourceIdentifiers: ["masvs-high-autocomplete-cache"], cwe: ["CWE-312"], cve: [], cvssScore: 7.1, description: "iOS/Android keyboard caches sensitive field inputs in plaintext.", labFeasible: true, firstDiscoveredYear: 2011, references: [SOURCE_REF] },
  { name: "OAuth Token Theft via Redirect URI Hijacking (Mobile)", severity: "high", sourceIdentifiers: ["masvs-high-oauth-redirect-hijack"], cwe: ["CWE-601"], cve: [], cvssScore: 7.5, description: "Malicious app registers same URL scheme intercepts OAuth auth code.", labFeasible: true, firstDiscoveredYear: 2016, references: [SOURCE_REF] },
  // ── Critical ─────────────────────────────────────────────────
  { name: "Remote Code Execution via WebView Universal Access", severity: "critical", sourceIdentifiers: ["masvs-crit-webview-rce"], cwe: ["CWE-749"], cve: [], cvssScore: 9.8, description: "setAllowUniversalAccessFromFileURLs + JS interface = unauthenticated RCE.", labFeasible: true, firstDiscoveredYear: 2012, references: [SOURCE_REF] },
  { name: "SQL Injection in Mobile Backend API", severity: "critical", sourceIdentifiers: ["masvs-crit-backend-sqli"], cwe: ["CWE-89"], cve: [], cvssScore: 9.8, description: "Mobile app parameter injected into backend API SQL query.", labFeasible: true, firstDiscoveredYear: 2010, references: [SOURCE_REF] },
  { name: "Authentication Token Theft via Exported Component", severity: "critical", sourceIdentifiers: ["masvs-crit-token-theft-exported"], cwe: ["CWE-926"], cve: [], cvssScore: 9.1, description: "Exported Activity or ContentProvider leaks auth tokens cross-app.", labFeasible: true, firstDiscoveredYear: 2011, references: [SOURCE_REF] },
  { name: "Arbitrary Code Execution via Unsafe Deserialization (Android)", severity: "critical", sourceIdentifiers: ["masvs-crit-android-deserial"], cwe: ["CWE-502"], cve: [], cvssScore: 9.8, description: "Android serialized object deserialized without class validation — RCE.", labFeasible: true, firstDiscoveredYear: 2015, references: [SOURCE_REF] },
  { name: "iOS URL Scheme Hijacking for OAuth Account Takeover", severity: "critical", sourceIdentifiers: ["masvs-crit-ios-url-hijack"], cwe: ["CWE-601"], cve: [], cvssScore: 9.3, description: "Malicious iOS app registers same URL scheme to steal OAuth authorization codes.", labFeasible: true, firstDiscoveredYear: 2015, references: [SOURCE_REF] },
  { name: "Unencrypted API Credential Storage — Full Account Takeover", severity: "critical", sourceIdentifiers: ["masvs-crit-plaintext-creds"], cwe: ["CWE-256"], cve: [], cvssScore: 9.8, description: "Plaintext stored credentials extracted from device leading to account takeover.", labFeasible: true, firstDiscoveredYear: 2010, references: [SOURCE_REF] },
];

export class OwaspMobileAdapter extends BaseAdapter {
  readonly adapterId = "owasp-masvs-v2";
  readonly domainId = "mobile" as const;

  async run(): Promise<AdapterResult> {
    try {
      const now = new Date().toISOString();
      const vulns: DetectorVulnerability[] = OWASP_MOBILE_VULNS.map((v) => ({
        ...v,
        canonicalId: this.canonicalId(this.domainId, this.adapterId, v.sourceIdentifiers[0]),
        normalizedName: this.normalizeName(v.name),
        sourceAdapterId: this.adapterId,
        domainId: this.domainId,
        detectedAt: now,
      }));
      return this.success(vulns);
    } catch (err) {
      return this.failure(String(err));
    }
  }
}
